wordpress_sites:
  vashonbuild.com:
    site_hosts:
      - canonical: vashonbuild.local
    local_path: ../site
    admin_email: developers@tinypixel.io
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false